X = str(input())
X = X.split(" ")
a = float(X[0])
b = float(X[1])
c = float(X[2])
print('TRIANGULO: {:.3f}'.format(((a * c) / 2)))
print('CIRCULO: {:.3f}'.format((3.14159 * (c ** 2))))
print('TRAPEZIO: {:.3f}'.format(((a + b) * c) / 2))
print('QUADRADO: {:.3f}'.format(b ** 2))
print('RETANGULO: {:.3f}'.format(a * b))